### ISSUE TITLE
InGameUI - 텍스트별로 표시되는 폭이 상이함

### ISSUE THREAD

**Issue by wooka000** [software-teamproject/BlocKing#11]
### 재현 환경
- 교수님이 올려주신 Demo program

### 재현 과정
1. 게임 시작
2. 블록을 쌓음

### 오류 내용
- 테두리와 블록의 칸을 계산했을때, 같은 칸임에도 그 길이가 상이함

### 기대 결과
- 텍스트가 같은 길이로 출력

### 재현 빈도
- 100%

### 기타 자료
- 첨부 사진 :
![image](https://user-images.githubusercontent.com/80891146/161196347-fe094339-a728-4297-8700-2b0fa92d01b3.png)

**Comment by gyuturn** [comment]
정상적으로 수정완료되었음
