### ISSUE TITLE
GameLogic - OBlock 생성되지 않음

### ISSUE THREAD

**Issue by oeccsy** [software-teamproject/BlocKing#26]
### 재현 환경
- dev 1.2

### 재현 과정
- getRandomBlock() 의 테스트 진행
- 그리고 게임 플레이 이후 생성되는 블럭의 종류를 관찰

### 오류 내용
- OBlock 이 생성되지 않음

### 기대 결과
- OBlock 생성

**Comment by oeccsy** [comment]
- BlockGenerator의 random int의 범위 수정하여 해결

**Comment by gyuturn** [comment]
수정확인 완료하였습니다!

**Comment by oeccsy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BlockGeneratorTest](https://trello.com/c/iun5uF0c/135-blockgeneratortest)
