### ISSUE TITLE
ROLLBACK - head : e4f187a

### ISSUE THREAD

**Issue by gyuturn** [software-teamproject/BlocKing#53]
## 발단
- #41 , #42  에서 dev2.1->Master 하려는 과정에서 dev1.2->Master 가 진행되었음

## 시도
- #43 ~ #52  에서 기존 PR을 REVERT

## 문제 확인
- 위의 해결 과정에서 commit이 섞여 서로 merge를 정상적으로 진행할 수 없게 됨

## 해결
- e4f187a 로 rollback 이후 규민님의 fork에서 작업하던 commit을 천천히 다시 push 하는 방식으로 해결함

**Comment by oeccsy** [comment]
더이상 관련 문제 없으므로 이슈 close 합니다.
